language: python
python:
  - "2.7"
  - "3.3"
install:
  - pip install six mock iso8601 backports.ssl-match-hostname --use-mirrors
  - python setup.py install
script:
  - RECURLY_INSECURE_DEBUG=true python -m unittest discover -s tests
